# ==========
# Imports
# ==========
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN
from sklearn.neighbors import KNeighborsClassifier
from hmmlearn.hmm import CategoricalHMM
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
import time



# ============
# File Paths
# ============

# have cherry picked these as they contain some of all, still maybe look for another file with theft in later
FULL_SOURCE_FILES = ["UNSW_2018_IoT_Botnet_Full5pc_2.csv",
                    "UNSW_2018_IoT_Botnet_Full5pc_4.csv",
                    "UNSW_2018_IoT_Botnet_Dataset_74.csv",
                    "Theft_Full.csv"]

BALANCED_FILE = "balanced_bot_iot.csv"                  # The output file we create/use
OUTPUT_SEQ_FILE = "novel_attack_sequences.npy"

# Need all of it
IMBALANCED_FILES = FULL_SOURCE_FILES



# ========================
# Toggles and Parameters
# ========================

# Toggles for what code is run
RECREATE_BALANCED_DATA = False  # Set to False if "balanced_bot_iot.csv" already exists
RECREATE_SEQUENCES = False      # Set to False if "novel_attack_sequences.npy" already exists

# Parameters
TARGET_SAMPLES_PER_CLASS = 3000
SEQ_LENGTH = 20 # have a graph printed now to justify this, maybe change to a little higher
STRIDE = 10 # should be half of seq_length for overlap, if above changes, change this
TEMPERATURE = 1.2 # see google doc for justification for why its not that large


# real dataset has 46 feaures, we are selecting a smaller subset of independent variables (14)
# to be generated by the CVAE, will fill in the others with alternative methods
# justfication - CVAEs cannot generate dependent variables well, If you ask a CVAE to generate both bytes and TnBPSrcIP,
# it will guess values that look statistically correct but are mathematically wrong, Tn... has to be >= bytes as its the history
FEATURES = [
    "dur",                                                      # how long
    "pkts", "spkts", "dpkts", "bytes", "sbytes", "dbytes",      # how much
    "rate", "srate", "drate",                                   # how fast
    "mean", "stddev", "min", "max"                              # how consistent
]



# ============================
# Building Balanced Dataset
# ============================

# Only end up with: {'DDoS': 3000, 'DoS': 3000, 'Reconnaissance': 3000, 'Theft': 79, 'Normal': 477}
# but this is fine, the fact that 'theft' is rare justifies using gen AI and not just a classifer
# normal traffic number is fine as its enough for context and not critical
# will however have to synthetically oversample theft to trick my CVAE into not treating it as noise
def create_balanced_dataset(input_path_list, output_path, target_samples):
    """
    Scans a list of large datasets and extracts a stratified sample of each category.
    """
    print("\n--- Creating Balanced Dataset from Multiple Files ---")
    
    # Buckets persist across all files
    # Matches the categories defined in the BoT-IoT dataset
    data_buckets = {
        "DDoS": [], "DoS": [], "Reconnaissance": [], "Theft": [], "Normal": []
    }
    
    chunk_size = 100000
    all_done = False # flag to break the outer loop if we finish early

    # Iterate through every file in the list
    for file_path in input_path_list:
        if all_done:
            break
            
        print(f"Scanning file: {file_path}...")

        try:
            # Process chunks within the current file
            for chunk in pd.read_csv(file_path, chunksize=chunk_size, low_memory=False):
                
                # Normalize column names
                if 'category' not in chunk.columns and 'attack_cat' in chunk.columns:
                    chunk.rename(columns={'attack_cat': 'category'}, inplace=True)
                
                if 'category' not in chunk.columns:
                    # Skip chunks/files with bad headers instead of crashing
                    print(f"Warning: Column 'category' not found in {file_path}. Skipping chunk.")
                    continue

                # Fill buckets
                for cat in data_buckets.keys():
                    current_count = sum([len(df) for df in data_buckets[cat]])
                    
                    if current_count < target_samples:
                        subset = chunk[chunk["category"] == cat]
                        if len(subset) > 0:
                            needed = target_samples - current_count
                            data_buckets[cat].append(subset.head(needed))

                # Check if ALL buckets are full
                total_counts = {k: sum([len(df) for df in v]) for k, v in data_buckets.items()}
                
                # Progress update
                print(f"Status: {total_counts}")

                if all(c >= target_samples for c in total_counts.values()):
                    print("All buckets full! Stopping scan.")
                    all_done = True
                    break
        
        except Exception as e:
            print(f"An error occurred reading {file_path}: {e}")
            continue # Try the next file even if this one fails

    # Combine and Save
    print("Combining extracted data...")
    frames = []
    for cat, bucket_list in data_buckets.items():
        if bucket_list:
            frames.append(pd.concat(bucket_list))
    
    if not frames:
        print("No data found in any files!")
        return

    balanced_df = pd.concat(frames)
    
    # Shuffle
    balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)
    
    print("\nFinal Balanced Distribution:")
    print(balanced_df["category"].value_counts())
    
    balanced_df.to_csv(output_path, index=False)
    print(f"Saved balanced dataset to '{output_path}'")


# Check if toggle for balancing data is True or False
if RECREATE_BALANCED_DATA:
    create_balanced_dataset(FULL_SOURCE_FILES, BALANCED_FILE, TARGET_SAMPLES_PER_CLASS)
else:
    print(f"\nSkipping data creation. Using existing '{BALANCED_FILE}'...")



# ================================================
# STEP 1 - LEARNING CLUSTERS OFF BALANCED DATA
# ================================================

# Find clusters based on this artificially balanced dataset, makes it easier for the model to find clusters
print("\n--- PHASE 1: Learning Vocabulary (Balanced Data) ---")

df_bal = pd.read_csv(BALANCED_FILE) # read in balanced file
# creates a new dataframe containing only the features specified above, changes infinities to NaN and deletes rows that contain a NaN
X_bal = df_bal[FEATURES].replace([np.inf, -np.inf], np.nan).dropna()

# Standardize and PCA from sklearn
scaler = StandardScaler()
X_bal_scaled = scaler.fit_transform(X_bal)

pca = PCA(n_components=5, random_state=42) # compresses features into 5
X_bal_pca = pca.fit_transform(X_bal_scaled)

# Clustering using DBSCAN from sklearn
# lowering eps to 0.1 and min_samples to 7, has created a lot more clusters, was 6 with eps=0.5 and min=20
# but with the old config there was no correlation between clusters and categories, now there are.
# 28 clusters with most now having one category, isolates rare attack vectors, granular behavioural clustering
# Cluster 0 is not a problem that it contains both recon and ddos because:
# Recon scan: Sends a tiny packet to Port 80. Waits for a tiny reply. (Short duration, small bytes).
# DDoS flood: Sends a tiny packet to Port 80. Doesn't wait. Repeats. (Short duration, small bytes).
# they are fundamentally the same shape so cannot separate them, will ignore, cluster 20 is the goldmine, only theft
dbscan = DBSCAN(eps=0.1, min_samples=5, n_jobs=-1)
bal_clusters = dbscan.fit_predict(X_bal_pca)

# Have to map DBSCAN clusters into a KNN configuration
# this is because DBSCAN doesn't have a .predict() function, meaning if you bring in a previously unseen
# datapoint it cannot say what cluster it belongs to, doesn't learn mathematical boundaries
# can't just run DBSCAN on the full imbalanced dataset due to computational limitations
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_bal_pca, bal_clusters) # feed the KNN the cluster mappings from DBSCAN

# Print number of clusters found and datapoints in each, should be equal to 'TARGET_SAMPLES_PER_CLASS' but isn't (thats fine)
print(f"Vocabulary Learned: {len(np.unique(bal_clusters))} Clusters Found.")
print(pd.Series(bal_clusters).value_counts())


# Prepare the dataframe
stats = X_bal.copy()
stats["cluster"] = bal_clusters #add the DBSCANs classification (cluster mapping)
stats["category"] = df_bal.loc[X_bal.index, "category"] #add the truth (category in dataset)


# Manual mappings based on the MITRE ATT%CK framework
# I am using the tactics only, not the specific techniques within those tactics, as that would require deep packet inspection
# which requires knowing the content of the payload, I only have the statistics in the csv

# Restriciting the scope to 4, not all 14 as network flow data is blind to the other 10.
# This is because some are host-based not network based (e.g. Privalege escalation - changing registry keys, have zero network footprint)
# selecting the only 4 tactics that inherently generate statistically distinct network signatures

# the dataset authors did not simulate complex lateral movement or credential access scenarios, talk about the limitation
# but overall this is still the best dataset - listed reasons in my google doc

def get_majority_label(cid, df_labeled):
    if cid == -1: return "Noise" # -1 is noise cluster in DBSCAN
    
    # Get all rows belonging to this cluster
    cluster_data = df_labeled[df_labeled['cluster'] == cid]

    # Find the most frequent category (mode)
    majority_category = cluster_data['category'].mode()[0]
    
    # Map the dataset category to a MITRE ATT&CK Tactic
    mapping = {
        "Theft":          "Exfiltration",
        "Reconnaissance": "Recon (Slow)",
        "DoS":            "Impact (DoS)",
        "DDoS":           "Impact (DoS)",
        "Normal":         "Benign"
    }
    
    return mapping.get(majority_category, "Unknown")

# Dictionary of cluster IDs to MITRE mappings
cluster_to_mitre = {}
# Get all unique cluster IDs and sort them (e.g., -1, 0, 1, 2...)
unique_clusters = sorted(stats["cluster"].unique())

for cid in unique_clusters:
    label = get_majority_label(cid, stats)
    cluster_to_mitre[cid] = label
    print(f"Cluster {cid}: {label}")


# Data preperation for HMM, it can't handle the -1 produced from the DBSCAN to represent noise
# so maps each integer up 1 effectively
# Moved this up as phase 2 is now skippable
le = LabelEncoder()
# Fit on the BALANCED clusters to ensure we know all possible states
le.fit(np.unique(bal_clusters)) # fitted on bal_clusters to ensure it knows about every attack state



# =========================================
# PHASE 1 - EXTRA PLOTS/ PRINT STATEMENTS
# =========================================


# PRINT LABELS IN EACH CLUSTER

# Sync the original dataframe with the cleaned feature set
# I use .loc[X_bal.index] to ensure I drop the same rows as earlier containing NaNs to align 1-1
df_clustered = df_bal.loc[X_bal.index].copy()
df_clustered['cluster'] = bal_clusters

print("\n--- Phase 1 Cluster Interpretations (Cherry Picked Data) ---")
unique_clusters = sorted(df_clustered['cluster'].unique())

# Iterate through each cluster to see what it contains
for cluster_id in unique_clusters:
    # Get all rows belonging to this cluster
    cluster_data = df_clustered[df_clustered['cluster'] == cluster_id]
    
    # Count the original categories in this cluster
    composition = cluster_data['category'].value_counts()
    
    # Calculate the centroid (average features)
    avg_bytes = cluster_data['bytes'].mean()
    avg_pkts = cluster_data['pkts'].mean()
    
    label = "NOISE" if cluster_id == -1 else f"Cluster {cluster_id}" # handle -1 case again
    
    # Print what labels are in a cluster and the average size
    print(f"\n[{label}] Total Points: {len(cluster_data)}")
    print(f"  -> Composition: {composition.to_dict()}")
    print(f"  -> Avg Profile: {avg_pkts:.1f} pkts, {avg_bytes:.1f} bytes")



# DIAGNOSTIC: STEP 1 CLUSTER MAP (K-MEANS)

print("\nGenerating Step 1 Cluster Map (Unsupervised)...")

# How many points to plot
SAMPLE_SIZE = 1000000

# We use 'stats' because that contains the raw K-Means output from Step 1
if 'stats' in locals() and 'cluster' in stats.columns:
    # Sample the data to avoid crashing the plotter
    plot_data = stats.sample(n=min(SAMPLE_SIZE, len(stats)), random_state=42)
else:
    print("Warning: 'stats' dataframe not found. Ensure Step 1 has run.")
    plot_data = None

if plot_data is not None:
    # Prepare Data
    X_plot = plot_data[FEATURES].values
    y_plot = plot_data['cluster'].values

    # Scale (Reuse global scaler)
    X_plot_scaled = scaler.transform(X_plot)

    # PCA Transform
    # We use the SAME PCA model as Step 2 so the axes (PC1/PC2) match perfectly.
    # This allows for a direct visual comparison.
    X_pca = pca.transform(X_plot_scaled)

    # 3. The Plot
    plt.figure(figsize=(14, 10))

    # Create scatter plot
    sns.scatterplot(
        x=X_pca[:, 0], 
        y=X_pca[:, 1], 
        hue=y_plot, 
        palette="tab20", 
        s=20, 
        alpha=0.6,
        legend="full"
    )

    # Highlight Cluster 17
    # Note: K-Means might have given Exfiltration a different ID in Step 1!
    if 17 in y_plot:
        c17_mask = (y_plot == 17)
        plt.scatter(
            X_pca[c17_mask, 0], 
            X_pca[c17_mask, 1], 
            c='black', 
            marker='x', 
            s=100, 
            linewidth=2,
            label='Cluster 17 (Step 1)'
        )

    plt.title(f"Step 1: Unsupervised Clustering (K-Means) - {len(np.unique(y_plot))} Clusters")
    plt.xlabel("Principal Component 1")
    plt.ylabel("Principal Component 2")

    # Legend placement
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)

    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("cluster_map_step1.png", dpi=300)
    plt.show()


# ==========================================
# VISUALIZATION: THE NEW THEFT LANDSCAPE
# ==========================================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

print("\nGenerating 'Theft Modalities' Plot...")

# 1. SETUP DATA
X_plot = X_bal.copy()
y_cluster = bal_clusters.copy() # Your new 43-cluster labels

# 2. DEFINE THE GROUPS
# We highlight the three behaviors we identified in the text logs
# Group A: The "Hiding" Theft (Cluster 0)
hiding_mask = (y_cluster == 0)

# Group B: The "Exfiltration" Theft (Cluster 17 is the biggest exfil group)
exfil_mask = (y_cluster == 17)

# Group C: The "Keylogging" Theft (Cluster 40 is the distinct micro-burst)
keylog_mask = (y_cluster == 40)

cluster_13 = (y_cluster == 13)

# Group D: Everything Else (Background)
background_mask = ~(hiding_mask | exfil_mask | keylog_mask)

# 3. GET PCA COORDINATES
X_pca_all = pca.transform(scaler.transform(X_plot))

# 4. PLOT
plt.figure(figsize=(12, 10))

# Plot Background (Grey)
plt.scatter(
    X_pca_all[background_mask, 0], 
    X_pca_all[background_mask, 1], 
    c='lightgrey', s=10, alpha=0.1, label='Other Traffic'
)

# Plot "Hiding" (Blue - same as Recon)
plt.scatter(
    X_pca_all[hiding_mask, 0], 
    X_pca_all[hiding_mask, 1], 
    c='blue', s=10, alpha=0.1, label='Cluster 0: "Hiding" State'
)

# Plot "Exfiltration" (Red - Heavy)
plt.scatter(
    X_pca_all[exfil_mask, 0], 
    X_pca_all[exfil_mask, 1], 
    c='red', marker='D', s=40, label='Cluster 17: Data Exfiltration'
)

# Plot "Keylogging" (Green - Bursty)
plt.scatter(
    X_pca_all[keylog_mask, 0], 
    X_pca_all[keylog_mask, 1], 
    c='lime', marker='^', s=60, edgecolors='black', label='Cluster 40: Keylogging Burst'
)

# Plot "C13"
plt.scatter(
    X_pca_all[keylog_mask, 0], 
    X_pca_all[keylog_mask, 1], 
    c='purple', marker='+', s=40, edgecolors='black', label='Cluster 13'
)

plt.title("The Three Faces of Theft: Hiding, Keylogging, and Exfiltration")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("theft_modalities.png", dpi=300)
plt.show()



# ==============================================
# STEP 2 - LEARN A MODEL OFF IMBALANCED DATA
# ==============================================

print("\n--- PHASE 2: Learning Grammar (Imbalanced Data) ---")

# Read every file in the list and store them
IMBALANCED_FILE_MAIN = []
for file_path in IMBALANCED_FILES:
    print(f"Reading {file_path}...")
    imbalanced_temp = pd.read_csv(file_path, low_memory=False)
    IMBALANCED_FILE_MAIN.append(imbalanced_temp)

# Stack them into one giant dataframe
df_imbal = pd.concat(IMBALANCED_FILE_MAIN, ignore_index=True)

# Clean the combined data
# (Select features, remove Infinity, remove NaNs)
X_imbal = df_imbal[FEATURES].replace([np.inf, -np.inf], np.nan).dropna()

print(f"Loaded Imbalanced Data: {X_imbal.shape}")

# Project into Balanced Space, use the same Scaler and PCA from step 1
X_imbal_scaled = scaler.transform(X_imbal)
X_imbal_pca = pca.transform(X_imbal_scaled) # compresses features down into 5 again

df_imbal = df_imbal.loc[X_imbal.index].copy() # handle the misalignment from NaN rows again

# Assign Labels using KNN
imbal_clusters = knn.predict(X_imbal_pca) # uses KNN representation to map imbalanced dataset to the clusters
df_imbal["cluster"] = imbal_clusters

print("Real-World Cluster Distribution (Should be skewed):")
print(pd.Series(imbal_clusters).value_counts())



# =========================================
# STEP 2 - EXTRA PLOTS/ PRINT STATEMENTS
# =========================================


# PRINT LABELS IN EACH CLUSTER

# Is exactly the same code as seeing step 1 label breakdown per cluster
print("\n--- Phase 2: Cluster Interpretations (Real-World Data) ---")

unique_imbal_clusters = sorted(df_imbal['cluster'].unique())

for cid in unique_imbal_clusters:
    cluster_data = df_imbal[df_imbal['cluster'] == cid]
    composition = cluster_data['category'].value_counts()

    avg_bytes = cluster_data['bytes'].mean()
    avg_pkts = cluster_data['pkts'].mean()

    label_name = "NOISE" if cid == -1 else f"Cluster {cid}"
    
    print(f"\n[{label_name}] Total Points: {len(cluster_data)}")
    print(f"  -> Composition: {composition.to_dict()}")
    print(f"  -> Avg Profile: {avg_pkts:.1f} pkts, {avg_bytes:.1f} bytes")



# DIAGNOSTIC: STEP 2 CLUSTER MAP (K-MEANS)

print("\nGenerating 2D Cluster Space Plot...")

# 1. Configuration
# We use a sample because plotting 1.6 million points is slow and messy
SAMPLE_SIZE = 100000

# Check which dataframe you have available. 
# Ideally use 'df_imbal' (Step 2 output) or 'stats' (Step 1 output).
if 'df_imbal' in locals():
    plot_data = df_imbal.sample(n=min(SAMPLE_SIZE, len(df_imbal)), random_state=42)
else:
    print("Warning: 'df_imbal' dataframe not found. Ensure Step 2 has run.")
    plot_data = None

# 2. Prepare Data for PCA
# We need strictly feature columns, dropping 'cluster', 'saddr', 'stime', etc.
X_plot = plot_data[FEATURES].values
y_plot = plot_data['cluster'].values

# reuse the scaler and PCA from before
X_plot_scaled = scaler.transform(X_plot)
X_pca = pca.transform(X_plot_scaled)

plt.figure(figsize=(14, 10))

# Create scatter plot with seaborn
# "palette='tab20'" creates distinct colors. 
# We filter out Noise (-1) usually, but let's keep it to see everything.
sns.scatterplot(
    x=X_pca[:, 0], 
    y=X_pca[:, 1], 
    hue=y_plot, 
    palette="tab20",  # High contrast palette
    s=20,             # Dot size
    alpha=0.6,        # Transparency
    legend="full"
)

# Highlight Cluster 17 (Exfiltration) specifically
c17_mask = (y_plot == 17)
plt.scatter(
    X_pca[c17_mask, 0], 
    X_pca[c17_mask, 1], 
    c='black', 
    marker='x', 
    s=100, 
    linewidth=2,
    label='TARGET: Exfiltration (17)'
)

plt.title(f"Cluster Separation Map (PCA Projection) - {len(np.unique(y_plot))} Clusters")
plt.xlabel("Principal Component 1 (Variance)")
plt.ylabel("Principal Component 2 (Variance)")

# Move legend outside because 28 items is tall
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)

plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("cluster_map_step2.png", dpi=300)
plt.show()



# ==========================================
# FORENSIC: WHERE DID THE REAL ATTACKS GO? (KNN Version)
# ==========================================

print("\nGenerating 'Captured vs. Escaped' Plot...")

# --- CONFIGURATION: UPDATE THIS ---
# 1. Column name for the attack type in your CSV
TARGET_COL = 'category'  # e.g., 'label', 'attack_cat', 'class'

# 2. Value for "Theft" in that column
THEFT_LABEL = 'Theft'   # e.g., 'Analysis', 'Backdoor', or 1
# ----------------------------------

# 1. FIND THE REAL THEFT PACKETS (Ground Truth)
if 'df_imbal' in locals() and TARGET_COL in df_imbal.columns:
    # Filter for the specific attack class
    if df_imbal[TARGET_COL].dtype == 'object':
        real_theft_mask = df_imbal[TARGET_COL] == THEFT_LABEL
    else:
        real_theft_mask = df_imbal[TARGET_COL] == 1 
        
    # Get the features and the Assigned Cluster for these specific packets
    X_real_theft = df_imbal.loc[real_theft_mask, FEATURES]
    assigned_clusters = df_imbal.loc[real_theft_mask, 'cluster'] # The labels from Step 2
    
    print(f"Found {len(X_real_theft)} Real Theft Packets in original data.")
else:
    raise ValueError(f"Column '{TARGET_COL}' not found in df_imbal.")

# 2. SPLIT INTO "CAPTURED" (Cluster 24) vs "ESCAPED" (Others)
detected_mask = (assigned_clusters == 17)
missed_mask = ~detected_mask

# 3. PREPARE PLOT DATA
# We need PCA coordinates for the map
# Use pandas to wrap features to avoid scaler warnings
X_real_theft_scaled = scaler.transform(X_real_theft)
X_real_theft_pca = pca.transform(X_real_theft_scaled)

X_detected_pca = X_real_theft_pca[detected_mask]
X_missed_pca = X_real_theft_pca[missed_mask]
missed_labels = assigned_clusters[missed_mask] 

# 4. APPLY JITTER (Essential for visibility)
jitter_strength = 0.5 

# Jitter for captured
if len(X_detected_pca) > 0:
    j_det_x = np.random.uniform(-1, 1, size=len(X_detected_pca)) * jitter_strength
    j_det_y = np.random.uniform(-1, 1, size=len(X_detected_pca)) * jitter_strength
else:
    j_det_x, j_det_y = [], []

# Jitter for missed
if len(X_missed_pca) > 0:
    j_miss_x = np.random.uniform(-1, 1, size=len(X_missed_pca)) * jitter_strength
    j_miss_y = np.random.uniform(-1, 1, size=len(X_missed_pca)) * jitter_strength
else:
    j_miss_x, j_miss_y = [], []

# 5. THE PLOT
plt.figure(figsize=(12, 10))

# A. Plot CAPTURED (Red Xs)
if len(X_detected_pca) > 0:
    plt.scatter(
        X_detected_pca[:, 0] + j_det_x, 
        X_detected_pca[:, 1] + j_det_y, 
        c='red', 
        marker='x', 
        s=100, 
        linewidth=2,
        label=f'Captured by Cluster 20 ({len(X_detected_pca)} pkts)'
    )

# B. Plot MISSED (Colored Circles)
if len(X_missed_pca) > 0:
    plt.scatter(
        X_missed_pca[:, 0] + j_miss_x, 
        X_missed_pca[:, 1] + j_miss_y, 
        c=missed_labels, 
        cmap='tab20', 
        marker='o', 
        s=80, 
        edgecolors='black',
        alpha=0.8,
        label=f'Missed / Misclassified ({len(X_missed_pca)} pkts)'
    )

plt.title("Forensic Analysis: Fate of the Real Theft Packets (Step 2)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(loc='upper right')
plt.grid(True, alpha=0.3)
plt.savefig("captured_vs_escaped_knn.png", dpi=300)
plt.show()

# 6. FORENSIC REPORT
print("\n--- ATTACK DETECTION REPORT ---")
print(f"Total Real Attacks Traced: {len(X_real_theft)}")
print(f"Correctly Identified (Cluster 20): {len(X_detected_pca)}")
print(f"Missed (False Negatives): {len(X_missed_pca)}")
if len(X_missed_pca) > 0:
    print("Where the missed attacks went (Wrong Cluster IDs):")
    print(missed_labels.value_counts().head(5))



# ==========================================
# DIAGNOSTIC: BURST LENGTH (TRUE THEFT VS FALSE ALARM)
# ==========================================
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

print("\nAnalyzing Burst Composition in Cluster 17...")

# --- CONFIGURATION ---
TARGET_CLUSTER = 17      # The cluster ID you are analyzing
# ---------------------

# 1. SETUP MASKS
# Mask for "The Model thinks this is Theft" (Cluster 24)
is_cluster_target = (imbal_clusters == TARGET_CLUSTER)

# Mask for "This is ACTUALLY Theft" (Ground Truth)
# (Ensure df_imbal is available from Step 2)
if df_imbal[TARGET_COL].dtype == 'object':
    is_real_theft = (df_imbal[TARGET_COL] == THEFT_LABEL)
else:
    is_real_theft = (df_imbal[TARGET_COL] == 1)

# 2. IDENTIFY BURSTS (Contiguous runs of Cluster 24)
# We give every distinct 'run' of packets a unique ID
cluster_series = pd.Series(is_cluster_target)
state_changes = cluster_series.ne(cluster_series.shift())
run_ids = state_changes.cumsum()

# 3. ANALYZE EACH BURST
# We create a temporary DataFrame to group by these Run IDs
analysis_df = pd.DataFrame({
    'run_id': run_ids,
    'in_cluster': is_cluster_target,
    'is_theft': is_real_theft.values
})

# Filter to keep only the runs that are actually inside Cluster 24
target_runs = analysis_df[analysis_df['in_cluster'] == True]

# Group by Run ID to get stats for each burst
burst_stats = target_runs.groupby('run_id').agg(
    burst_length=('in_cluster', 'count'),      # How long is the burst?
    real_theft_count=('is_theft', 'sum')       # How many REAL theft packets are in it?
)

# 4. SPLIT INTO "TRUE ATTACKS" AND "FALSE ALARMS"
# True Attack Burst: Contains at least one real theft packet
true_attack_bursts = burst_stats[burst_stats['real_theft_count'] > 0]['burst_length']

# False Alarm Burst: Contains ZERO real theft packets (Pure Noise)
false_alarm_bursts = burst_stats[burst_stats['real_theft_count'] == 0]['burst_length']

print(f"Found {len(true_attack_bursts)} Valid Attack Bursts")
print(f"Found {len(false_alarm_bursts)} False Alarm Bursts")

# 5. PLOT OVERLAPPING HISTOGRAMS
plt.figure(figsize=(12, 7))

# Plot False Alarms (Noise) usually short, in Blue/Grey
sns.histplot(
    false_alarm_bursts, 
    color='grey', 
    label=f'False Alarms (Noise) - Mean: {false_alarm_bursts.mean():.1f}', 
    kde=False, 
    stat="density", # Normalize so we can compare shapes even if counts differ
    alpha=0.4,
    binwidth=2
)

# Plot True Attacks (Theft) in Red
sns.histplot(
    true_attack_bursts, 
    color='red', 
    label=f'True Theft Flows - Mean: {true_attack_bursts.mean():.1f}', 
    kde=True, 
    stat="density",
    alpha=0.5,
    binwidth=2
)

plt.axvline(x=20, color='black', linestyle='--', linewidth=2, label='Selected Length (20)')

plt.title(f"Burst Length Analysis: True Attacks vs. False Alarms (Cluster {TARGET_CLUSTER})")
plt.xlabel("Consecutive Packets (Burst Length)")
plt.ylabel("Density (Normalized Frequency)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("burst_length_comparison.png", dpi=300)
plt.show()

# 6. FORENSIC SUMMARY
print("\n--- FORENSIC INSIGHT ---")
print(f"True Attack Mean Length: {true_attack_bursts.mean():.2f}")
print(f"False Alarm Mean Length: {false_alarm_bursts.mean():.2f}")

if false_alarm_bursts.mean() < true_attack_bursts.mean():
    print("INSIGHT: False positives are significantly shorter than real attacks.")
    print("Recommendation: You can filter out noise by ignoring bursts < 5 packets.")



# ================================
# STEP 2.5 - TRAINING THE HMM
# ================================

import numpy as np
import pandas as pd
from scipy.special import softmax

class SupervisedMarkovChain:
    def __init__(self):
        # RENAMED to match hmmlearn standard (fixes your Phase 3 error)
        self.transmat_ = None 
        self.states = []
        self.state_to_idx = {}
        self.idx_to_state = {}
        self.state_feature_stats = {} 

    def fit(self, df, cluster_col='cluster', label_col='category', feature_cols=None):
        print("Building Composite States (Cluster + Label)...")
        
        # 1. Create Composite Column
        df['composite_state'] = df[cluster_col].astype(str) + "_" + df[label_col].astype(str)
        
        # 2. Map unique states
        unique_states = sorted(df['composite_state'].unique())
        self.states = unique_states
        self.state_to_idx = {state: i for i, state in enumerate(unique_states)}
        self.idx_to_state = {i: state for i, state in enumerate(unique_states)}
        n_states = len(unique_states)
        
        print(f"Identified {n_states} unique composite states.")

        # 3. Count Transitions
        trans_counts = np.ones((n_states, n_states)) * 1e-6 # Laplace smoothing
        
        grouped = df.sort_values("stime").groupby("saddr")
        for saddr, group in grouped:
            seq = group['composite_state'].values
            if len(seq) < 2: continue
            
            indices = [self.state_to_idx[s] for s in seq]
            for t in range(len(indices) - 1):
                trans_counts[indices[t], indices[t+1]] += 1

        # 4. Normalize to Probabilities (transmat_)
        self.transmat_ = trans_counts / trans_counts.sum(axis=1, keepdims=True)
        
        # 5. Robust Feature Profiling (Fixes the Divide by Zero / Covariance error)
        if feature_cols:
            print("Calculating robust feature profiles...")
            for state in unique_states:
                subset = df[df['composite_state'] == state][feature_cols]
                
                # Handle 'Singleton' States (only 1 packet found)
                if len(subset) > 1:
                    mean_vec = subset.mean().values
                    # Add tiny noise to diagonal to prevent singular matrix errors later
                    cov_mx = subset.cov().values + (np.eye(len(feature_cols)) * 1e-6)
                else:
                    # If only 1 packet exists, variance is zero. 
                    # We set a tiny 'synthetic' variance so we can still sample from it.
                    mean_vec = subset.iloc[0].values
                    cov_mx = np.eye(len(feature_cols)) * 1e-6
                
                self.state_feature_stats[state] = {
                    'mean': mean_vec,
                    'cov': cov_mx
                }
        
        print("Supervised Markov Chain Trained Successfully.")

    def apply_temperature(self, temperature=1.0):
        # Work on self.transmat_
        log_probs = np.log(self.transmat_ + 1e-9)
        scaled_logits = log_probs / temperature
        self.transmat_ = softmax(scaled_logits, axis=1)
        print(f"Transition matrix scaled with Temperature={temperature}")

    def generate_sequence(self, start_state, length=10):
        if start_state not in self.state_to_idx:
            raise ValueError(f"Start state '{start_state}' not found in model. Available: {self.states[:5]}...")
            
        current_idx = self.state_to_idx[start_state]
        sequence = [start_state]
        
        for _ in range(length - 1):
            probs = self.transmat_[current_idx]
            next_idx = np.random.choice(len(self.states), p=probs)
            sequence.append(self.idx_to_state[next_idx])
            current_idx = next_idx
            
        return sequence

# ==========================================
# NEW: HELPER FUNCTIONS FOR GENERATION
# ==========================================

def print_available_composites(model):
    """
    Prints all available composite states grouped by their category 
    so you can easily copy-paste them into your target list.
    """
    print("\n--- AVAILABLE COMPOSITE STATES ---") # might want to make this filter under 5 samples out or something
    
    # Group by the text part (Label) for easier reading
    organized = {}
    for state in model.states:
        # Assuming format "ClusterID_Label"
        parts = state.split('_')
        label = parts[-1] 
        if label not in organized:
            organized[label] = []
        organized[label].append(state)
        
    for label, states in organized.items():
        print(f"\n[{label.upper()}]:")
        # Print in chunks of 5 to keep it tidy
        for i in range(0, len(states), 5):
            print(f"  {states[i:i+5]}")
    print("\n----------------------------------")

# 1. The Helper Function for Temperature
def get_scaled_transition_matrix(trans_mat, T=1.0):
    """
    Returns a new transition matrix with temperature scaling applied.
    T < 1.0: Sharpening (Makes likely transitions even MORE likely).
    T > 1.0: Flattening (Increases randomness/exploration).
    """
    if T == 1.0:
        return trans_mat.copy()
    
    # Use power method to scale probabilities while preserving 0.0 constraints
    # (We don't want to create transitions that are impossible)
    scaled = np.power(trans_mat, 1.0 / T)
    
    # Re-normalize rows so they sum to 1.0
    row_sums = scaled.sum(axis=1, keepdims=True)
    # Avoid division by zero if a row is all zeros (dead end)
    row_sums[row_sums == 0] = 1.0
    
    return scaled / row_sums


def generate_and_save_traffic(model, target_states, samples_per_state=10, temperature=1.0, seq_len=20, output_file="synthetic_traffic.csv"):
    """
    1. Iterates through the list of 'target_states'.
    2. Generates 'samples_per_state' sequences for each.
    3. Reconstructs packet features (Total Len, Dload, etc.) using the State Stats.
    4. Saves to CSV.
    """
    all_data = []
    feature_names = list(model.state_feature_stats[model.states[0]]['mean'].shape) # infer dimension
    # Ideally, we want the original column names. 
    # If you passed feature_cols to fit(), we assume the order is preserved.
    # We will use generic names if we can't find them, but usually 
    # you know what FEATURES you passed in.

    # --- STEP A: TEMPORARY MODEL MODIFICATION ---
    # We back up the original matrix so we don't break the model permanently
    original_transmat = model.transmat_.copy()
    
    if temperature != 1.0:
        print(f"🔥 Applying Temperature T={temperature} (Scaling probabilities)...")
        model.transmat_ = get_scaled_transition_matrix(original_transmat, T=temperature)
    
    print(f"\nStarting Generation Pipeline (T={temperature})...")
    print(f"Targeting {len(target_states)} specific composite types.")
    print(f"Generating {samples_per_state} sequences per type.")

    try:
        for start_node in target_states:
            if start_node not in model.state_to_idx:
                print(f"WARNING: Skipping {start_node} (Not found in model)")
                continue
                
            print(f"  -> Generating for {start_node}...")
            
            for i in range(samples_per_state):
                # 1. Generate State Sequence
                try:
                    seq_states = model.generate_sequence(start_state=start_node, length=seq_len)
                except Exception as e:
                    print(f"     Error generating from {start_node}: {e}")
                    continue

                # 2. Reconstruct Features (The "Cheat" Method)
                for t, state in enumerate(seq_states):
                    stats = model.state_feature_stats.get(state)
                    
                    if stats:
                        # Sample from Gaussian (Mean + Covariance)
                        # This creates the specific packet characteristics for this Cluster+Label
                        feats = np.random.multivariate_normal(stats['mean'], stats['cov'])
                        feats = np.maximum(feats, 0) # Physics check (no negative bytes)
                        
                        # Create Row
                        row = {
                            'sequence_id': f"{start_node}_{i}_T{temperature}", # Unique ID for this flow
                            'step': t,
                            'composite_state': state,
                            'label': state.split('_')[-1], # Extract "Theft" from "17_Theft"
                            # We map features to columns 0, 1, 2... 
                            # Update these keys to match your FEATURES list!
                            'feat_0': feats[0], 
                            'feat_1': feats[1],
                            'feat_2': feats[2]
                        }
                        all_data.append(row)

    finally:
        # --- STEP C: RESTORE MODEL ---
        # Always restore original matrix, even if code crashes
        if temperature != 1.0:
            model.transmat_ = original_transmat
            print("❄️ Restored original transition probabilities.")

    # 3. Save to File
    if all_data:
        df_gen = pd.DataFrame(all_data)
        
        # Rename generic feature columns if we know the inputs
        # CHANGE THIS LIST to match your actual FEATURES variable
        feature_map = {
            'feat_0': 'total_len', 
            'feat_1': 'proto_number', 
            'feat_2': 'dload'
        }
        df_gen.rename(columns=feature_map, inplace=True)
        
        df_gen.to_csv(output_file, index=False)
        print(f"\nSUCCESS: Generated {len(df_gen)} packets.")
        print(f"Saved to: {output_file}")
        return df_gen
    else:
        print("\nFAILED: No data generated.")
        return None
    

# ==========================================
# FIX: SANITIZE DATA TYPES BEFORE FITTING
# ==========================================

# 1. Define your features list explicitly if you haven't already
# (Make sure these match exactly what you want to generate)

print("Checking data types BEFORE fix:")
print(df_imbal[FEATURES].dtypes)

# 2. Force conversion to numeric (coercing errors to NaN)
for col in FEATURES:
    # This turns strings like "100" into 100.0
    # It turns junk like "Infinity" or "Text" into NaN
    df_imbal[col] = pd.to_numeric(df_imbal[col], errors='coerce')

# 3. Fill the NaNs we just created (important!)
# If 'dload' was Infinity, we replace it with the max valid value or 0
df_imbal.fillna(0, inplace=True)

print("\nChecking data types AFTER fix (Should all be float/int):")
print(df_imbal[FEATURES].dtypes)


# ==========================================
# EXECUTION BLOCK
# ==========================================

# 1. Train (Assuming df_imbal and FEATURES are already defined)
hmm_supervised = SupervisedMarkovChain()
hmm_supervised.fit(df_imbal, cluster_col='cluster', label_col='category', feature_cols=FEATURES)

# 2. VIEW what composites exist (so you can choose)
print_available_composites(hmm_supervised)

# 3. DEFINE your wish list
# You can copy-paste these from the print output above
my_target_states = [
    '17_Theft',      # Specific cluster theft
    '-1_Theft',      # Noise theft
    '10_DoS',        # Standard DoS
    '14_Reconnaissance', # Some recon
    '0_Normal'
]


# Generate Standard Traffic (T=1.0)
# This mimics the training data exactly.
df_std = generate_and_save_traffic(
    model=hmm_supervised, 
    target_states=my_target_states, 
    samples_per_state=50,
    seq_len=20,
    temperature=1.0,
    output_file="synthetic_traffic_standard.csv"
)

# Generate "Zero-Day" Traffic (T=1.3)
# This allows the model to take "rarer" paths, simulating slightly different attack variants.
df_wild = generate_and_save_traffic(
    model=hmm_supervised, 
    target_states=my_target_states, 
    samples_per_state=50,
    seq_len=20,
    temperature=1.3,
    output_file="synthetic_traffic_zeroday.csv"
)

# 5. Quick Peek
if df_wild is not None:
    print(df_wild.head())


def inspect_transition_probabilities(model, state_name):
    """
    Prints the top 5 most likely next states for a given state.
    """
    if state_name not in model.state_to_idx:
        print(f"State {state_name} not found.")
        return

    # Get the row of probabilities for this state
    idx = model.state_to_idx[state_name]
    probs = model.transmat_[idx]
    
    # Sort indices by probability (descending)
    sorted_indices = np.argsort(probs)[::-1]
    
    print(f"\n--- TRANSITIONS FROM {state_name} ---")
    print(f"Total packets observed in training: {probs.sum() if probs.sum() > 1 else 'Normalized'}")
    
    # Print top 5 destinations
    for i in range(5):
        next_idx = sorted_indices[i]
        prob = probs[next_idx]
        if prob > 0.001: # Only show > 0.1% chance
            next_state = model.idx_to_state[next_idx]
            print(f"  -> {next_state}: {prob:.2%} chance")


inspect_transition_probabilities(hmm_supervised, '17_Theft')
inspect_transition_probabilities(hmm_supervised, '-1_Theft')
inspect_transition_probabilities(hmm_supervised, '10_Dos')
inspect_transition_probabilities(hmm_supervised, '0_Normal')
inspect_transition_probabilities(hmm_supervised, '14_Reconnaissance')