# ==========
# Imports
# ==========
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN
from sklearn.neighbors import KNeighborsClassifier
from hmmlearn.hmm import CategoricalHMM
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
import time



# ============
# File Paths
# ============

# Cherry pick these, will want to test multiple datasets here
FULL_SOURCE_FILES = ["UNSW_2018_IoT_Botnet_Full5pc_2.csv",
                    "UNSW_2018_IoT_Botnet_Full5pc_4.csv",
                    "UNSW_2018_IoT_Botnet_Dataset_74.csv",
                    "Theft_Full.csv"]

BALANCED_FILE = "balanced_bot_iot.csv"                  # The output files we create/use
OUTPUT_SEQ_FILE = "novel_attack_sequences.npy"

# Need all of it
IMBALANCED_FILES = FULL_SOURCE_FILES



# ========================
# Toggles and Parameters
# ========================

# Toggles for what code is run
RECREATE_BALANCED_DATA = False  # Set to False if "balanced_bot_iot.csv" already exists
RECREATE_SEQUENCES = False      # Set to False if "novel_attack_sequences.npy" already exists

# Parameters
TARGET_SAMPLES_PER_CLASS = 3000
SEQ_LENGTH = 20 # have a graph printed now to justify this, maybe change to a little higher
STRIDE = 10 # should be half of seq_length for overlap, if above changes, change this
TEMPERATURE = 1.2 # see google doc for justification for why its not that large


# real dataset has 46 feaures, we are selecting a smaller subset of independent variables (14)
# to be generated by the CVAE, will fill in the others with alternative methods
# justfication - CVAEs cannot generate dependent variables well, If you ask a CVAE to generate both bytes and TnBPSrcIP,
# it will guess values that look statistically correct but are mathematically wrong, Tn... has to be >= bytes as its the history
# THESE FEATURES WILL ALSO CHANGE DEPENDING ON DATASET
FEATURES = [
    "dur",                                                      # how long
    "pkts", "spkts", "dpkts", "bytes", "sbytes", "dbytes",      # how much
    "rate", "srate", "drate",                                   # how fast
    "mean", "stddev", "min", "max"                              # how consistent
]



# ============================
# Building Balanced Dataset
# ============================

# Only end up with: {'DDoS': 3000, 'DoS': 3000, 'Reconnaissance': 3000, 'Theft': 79, 'Normal': 477}
# but this is fine, the fact that 'theft' is rare justifies using gen AI and not just a classifer
# normal traffic number is fine as its enough for context and not critical
# will however have to synthetically oversample theft to trick my CVAE into not treating it as noise
def create_balanced_dataset(input_path_list, output_path, target_samples):
    """
    Scans a list of large datasets and extracts a stratified sample of each category.
    """
    print("\n--- Creating Balanced Dataset from Multiple Files ---")
    
    # Buckets persist across all files
    # Matches the categories defined in the BoT-IoT dataset
    data_buckets = {
        "DDoS": [], "DoS": [], "Reconnaissance": [], "Theft": [], "Normal": []  # WILL NEED TO MANUALLY CHANGE THESE TOO
    }
    
    chunk_size = 100000
    all_done = False # flag to break the outer loop if we finish early

    # Iterate through every file in the list
    for file_path in input_path_list:
        if all_done:
            break
            
        print(f"Scanning file: {file_path}...")

        try:
            # Process chunks within the current file
            for chunk in pd.read_csv(file_path, chunksize=chunk_size, low_memory=False):
                
                # Normalize column names
                if 'category' not in chunk.columns and 'attack_cat' in chunk.columns:
                    chunk.rename(columns={'attack_cat': 'category'}, inplace=True)
                
                if 'category' not in chunk.columns:
                    # Skip chunks/files with bad headers instead of crashing
                    print(f"Warning: Column 'category' not found in {file_path}. Skipping chunk.")
                    continue

                # Fill buckets
                for cat in data_buckets.keys():
                    current_count = sum([len(df) for df in data_buckets[cat]])
                    
                    if current_count < target_samples:
                        subset = chunk[chunk["category"] == cat]
                        if len(subset) > 0:
                            needed = target_samples - current_count
                            data_buckets[cat].append(subset.head(needed))

                # Check if ALL buckets are full
                total_counts = {k: sum([len(df) for df in v]) for k, v in data_buckets.items()}
                
                # Progress update
                print(f"Status: {total_counts}")

                if all(c >= target_samples for c in total_counts.values()):
                    print("All buckets full! Stopping scan.")
                    all_done = True
                    break
        
        except Exception as e:
            print(f"An error occurred reading {file_path}: {e}")
            continue # Try the next file even if this one fails

    # Combine and Save
    print("Combining extracted data...")
    frames = []
    for cat, bucket_list in data_buckets.items():
        if bucket_list:
            frames.append(pd.concat(bucket_list))
    
    if not frames:
        print("No data found in any files!")
        return

    balanced_df = pd.concat(frames)
    
    # Shuffle
    balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)
    
    print("\nFinal Balanced Distribution:")
    print(balanced_df["category"].value_counts())
    
    balanced_df.to_csv(output_path, index=False)
    print(f"Saved balanced dataset to '{output_path}'")


# Check if toggle for balancing data is True or False
if RECREATE_BALANCED_DATA:
    create_balanced_dataset(FULL_SOURCE_FILES, BALANCED_FILE, TARGET_SAMPLES_PER_CLASS)
else:
    print(f"\nSkipping data creation. Using existing '{BALANCED_FILE}'...")



# ================================================
# STEP 1 - LEARNING CLUSTERS OFF BALANCED DATA
# ================================================

# Find clusters based on this artificially balanced dataset, makes it easier for the model to find clusters
print("\n--- PHASE 1: Learning Vocabulary (Balanced Data) ---")

df_bal = pd.read_csv(BALANCED_FILE) # read in balanced file
# creates a new dataframe containing only the features specified above, changes infinities to NaN and deletes rows that contain a NaN
X_bal = df_bal[FEATURES].replace([np.inf, -np.inf], np.nan).dropna()

# Standardize and PCA from sklearn
scaler = StandardScaler()
X_bal_scaled = scaler.fit_transform(X_bal)

pca = PCA(n_components=5, random_state=42) # compresses features into 5
X_bal_pca = pca.fit_transform(X_bal_scaled)

# Clustering using DBSCAN from sklearn
# lowering eps to 0.1 and min_samples to 7, has created a lot more clusters, was 6 with eps=0.5 and min=20
# but with the old config there was no correlation between clusters and categories, now there are.
# 28 clusters with most now having one category, isolates rare attack vectors, granular behavioural clustering
# Cluster 0 is not a problem that it contains both recon and ddos because:
# Recon scan: Sends a tiny packet to Port 80. Waits for a tiny reply. (Short duration, small bytes).
# DDoS flood: Sends a tiny packet to Port 80. Doesn't wait. Repeats. (Short duration, small bytes).
# they are fundamentally the same shape so cannot separate them, will ignore, cluster 20 is the goldmine, only theft
dbscan = DBSCAN(eps=0.1, min_samples=5, n_jobs=-1)
bal_clusters = dbscan.fit_predict(X_bal_pca)

# Have to map DBSCAN clusters into a KNN configuration
# this is because DBSCAN doesn't have a .predict() function, meaning if you bring in a previously unseen
# datapoint it cannot say what cluster it belongs to, doesn't learn mathematical boundaries
# can't just run DBSCAN on the full imbalanced dataset due to computational limitations
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_bal_pca, bal_clusters) # feed the KNN the cluster mappings from DBSCAN

# Print number of clusters found and datapoints in each, should be equal to 'TARGET_SAMPLES_PER_CLASS' but isn't (thats fine)
print(f"Vocabulary Learned: {len(np.unique(bal_clusters))} Clusters Found.")
print(pd.Series(bal_clusters).value_counts())


# Prepare the dataframe
stats = X_bal.copy()
stats["cluster"] = bal_clusters #add the DBSCANs classification (cluster mapping)
stats["category"] = df_bal.loc[X_bal.index, "category"] #add the truth (category in dataset)


# Manual mappings based on the MITRE ATT%CK framework
# I am using the tactics only, not the specific techniques within those tactics, as that would require deep packet inspection
# which requires knowing the content of the payload, I only have the statistics in the csv

# Restriciting the scope to 4, not all 14 as network flow data is blind to the other 10.
# This is because some are host-based not network based (e.g. Privalege escalation - changing registry keys, have zero network footprint)
# selecting the only 4 tactics that inherently generate statistically distinct network signatures

# the dataset authors did not simulate complex lateral movement or credential access scenarios, talk about the limitation
# but overall this is still the best dataset - listed reasons in my google doc

def get_majority_label(cid, df_labeled):
    if cid == -1: return "Noise" # -1 is noise cluster in DBSCAN
    
    # Get all rows belonging to this cluster
    cluster_data = df_labeled[df_labeled['cluster'] == cid]

    # Find the most frequent category (mode)
    majority_category = cluster_data['category'].mode()[0]
    
    # Map the dataset category to a MITRE ATT&CK Tactic
    # THESE WILL AGAIN CHANGE WITH THE DATASET
    mapping = {
        "Theft":          "Exfiltration",
        "Reconnaissance": "Recon (Slow)",
        "DoS":            "Impact (DoS)",
        "DDoS":           "Impact (DoS)",
        "Normal":         "Benign"
    }
    
    return mapping.get(majority_category, "Unknown")

# Dictionary of cluster IDs to MITRE mappings
cluster_to_mitre = {}
# Get all unique cluster IDs and sort them (e.g., -1, 0, 1, 2...)
unique_clusters = sorted(stats["cluster"].unique())

for cid in unique_clusters:
    label = get_majority_label(cid, stats)
    cluster_to_mitre[cid] = label
    print(f"Cluster {cid}: {label}")


# Data preperation for HMM, it can't handle the -1 produced from the DBSCAN to represent noise
# so maps each integer up 1 effectively
# Moved this up as phase 2 is now skippable
le = LabelEncoder()
# Fit on the BALANCED clusters to ensure we know all possible states
le.fit(np.unique(bal_clusters)) # fitted on bal_clusters to ensure it knows about every attack state



# =========================================
# PHASE 1 - EXTRA PLOTS/ PRINT STATEMENTS
# =========================================


# PRINT LABELS IN EACH CLUSTER

# Sync the original dataframe with the cleaned feature set
# I use .loc[X_bal.index] to ensure I drop the same rows as earlier containing NaNs to align 1-1
df_clustered = df_bal.loc[X_bal.index].copy()
df_clustered['cluster'] = bal_clusters

print("\n--- Phase 1 Cluster Interpretations (Cherry Picked Data) ---")
unique_clusters = sorted(df_clustered['cluster'].unique())

# Iterate through each cluster to see what it contains
for cluster_id in unique_clusters:
    # Get all rows belonging to this cluster
    cluster_data = df_clustered[df_clustered['cluster'] == cluster_id]
    
    # Count the original categories in this cluster
    composition = cluster_data['category'].value_counts()
    
    # Calculate the centroid (average features)
    avg_bytes = cluster_data['bytes'].mean()
    avg_pkts = cluster_data['pkts'].mean()
    
    label = "NOISE" if cluster_id == -1 else f"Cluster {cluster_id}" # handle -1 case again
    
    # Print what labels are in a cluster and the average size
    print(f"\n[{label}] Total Points: {len(cluster_data)}")
    print(f"  -> Composition: {composition.to_dict()}")
    print(f"  -> Avg Profile: {avg_pkts:.1f} pkts, {avg_bytes:.1f} bytes")



# DIAGNOSTIC: STEP 1 CLUSTER MAP (K-MEANS)

print("\nGenerating Step 1 Cluster Map (Unsupervised)...")

# How many points to plot
SAMPLE_SIZE = 1000000

# We use 'stats' because that contains the raw K-Means output from Step 1
if 'stats' in locals() and 'cluster' in stats.columns:
    # Sample the data to avoid crashing the plotter
    plot_data = stats.sample(n=min(SAMPLE_SIZE, len(stats)), random_state=42)
else:
    print("Warning: 'stats' dataframe not found. Ensure Step 1 has run.")
    plot_data = None

if plot_data is not None:
    # Prepare Data
    X_plot = plot_data[FEATURES].values
    y_plot = plot_data['cluster'].values

    # Scale (Reuse global scaler)
    X_plot_scaled = scaler.transform(X_plot)

    # PCA Transform
    # We use the SAME PCA model as Step 2 so the axes (PC1/PC2) match perfectly.
    # This allows for a direct visual comparison.
    X_pca = pca.transform(X_plot_scaled)

    # 3. The Plot
    plt.figure(figsize=(14, 10))

    # Create scatter plot
    sns.scatterplot(
        x=X_pca[:, 0], 
        y=X_pca[:, 1], 
        hue=y_plot, 
        palette="tab20", 
        s=20, 
        alpha=0.6,
        legend="full"
    )

    # Highlight Cluster 17 - this cluster will change with tests
    if 17 in y_plot:
        c17_mask = (y_plot == 17)
        plt.scatter(
            X_pca[c17_mask, 0], 
            X_pca[c17_mask, 1], 
            c='black', 
            marker='x', 
            s=100, 
            linewidth=2,
            label='Cluster 17 (Step 1)'
        )

    plt.title(f"Step 1: Unsupervised Clustering (K-Means) - {len(np.unique(y_plot))} Clusters")
    plt.xlabel("Principal Component 1")
    plt.ylabel("Principal Component 2")

    # Legend placement
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)

    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("cluster_map_step1.png", dpi=300)
    plt.show()


# ==========================================
# VISUALIZATION: THE NEW THEFT LANDSCAPE
# ==========================================

# THIS IS MEGA SPECIFIC TO 1ST TESTING SET

print("\nGenerating 'Theft Modalities' Plot...")

# 1. SETUP DATA
X_plot = X_bal.copy()
y_cluster = bal_clusters.copy() # Your new 43-cluster labels

# 2. DEFINE THE GROUPS
# We highlight the three behaviors we identified in the text logs
# Group A: The "Hiding" Theft (Cluster 0)
hiding_mask = (y_cluster == 0)

# Group B: The "Exfiltration" Theft (Cluster 17 is the biggest exfil group)
exfil_mask = (y_cluster == 17)

# Group C: The "Keylogging" Theft (Cluster 40 is the distinct micro-burst)
keylog_mask = (y_cluster == 40)

cluster_13 = (y_cluster == 13)

# Group D: Everything Else (Background)
background_mask = ~(hiding_mask | exfil_mask | keylog_mask)

# 3. GET PCA COORDINATES
X_pca_all = pca.transform(scaler.transform(X_plot))

# 4. PLOT
plt.figure(figsize=(12, 10))

# Plot Background (Grey)
plt.scatter(
    X_pca_all[background_mask, 0], 
    X_pca_all[background_mask, 1], 
    c='lightgrey', s=10, alpha=0.1, label='Other Traffic'
)

# Plot "Hiding" (Blue - same as Recon)
plt.scatter(
    X_pca_all[hiding_mask, 0], 
    X_pca_all[hiding_mask, 1], 
    c='blue', s=10, alpha=0.1, label='Cluster 0: "Hiding" State'
)

# Plot "Exfiltration" (Red - Heavy)
plt.scatter(
    X_pca_all[exfil_mask, 0], 
    X_pca_all[exfil_mask, 1], 
    c='red', marker='D', s=40, label='Cluster 17: Data Exfiltration'
)

# Plot "Keylogging" (Green - Bursty)
plt.scatter(
    X_pca_all[keylog_mask, 0], 
    X_pca_all[keylog_mask, 1], 
    c='lime', marker='^', s=60, edgecolors='black', label='Cluster 40: Keylogging Burst'
)

# Plot "C13"
plt.scatter(
    X_pca_all[keylog_mask, 0], 
    X_pca_all[keylog_mask, 1], 
    c='purple', marker='+', s=40, edgecolors='black', label='Cluster 13'
)

plt.title("The Three Faces of Theft: Hiding, Keylogging, and Exfiltration")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("theft_modalities.png", dpi=300)
plt.show()



# ==============================================
# STEP 2 - LEARN A MODEL OFF IMBALANCED DATA
# ==============================================

print("\n--- PHASE 2: Learning Grammar (Imbalanced Data) ---")

# Read every file in the list and store them
IMBALANCED_FILE_MAIN = []
for file_path in IMBALANCED_FILES:
    print(f"Reading {file_path}...")
    imbalanced_temp = pd.read_csv(file_path, low_memory=False)
    IMBALANCED_FILE_MAIN.append(imbalanced_temp)

# Stack them into one giant dataframe
df_imbal = pd.concat(IMBALANCED_FILE_MAIN, ignore_index=True)

# Clean the combined data
# (Select features, remove Infinity, remove NaNs)
X_imbal = df_imbal[FEATURES].replace([np.inf, -np.inf], np.nan).dropna()

print(f"Loaded Imbalanced Data: {X_imbal.shape}")

# Project into Balanced Space, use the same Scaler and PCA from step 1
X_imbal_scaled = scaler.transform(X_imbal)
X_imbal_pca = pca.transform(X_imbal_scaled) # compresses features down into 5 again

df_imbal = df_imbal.loc[X_imbal.index].copy() # handle the misalignment from NaN rows again

# Assign Labels using KNN
imbal_clusters = knn.predict(X_imbal_pca) # uses KNN representation to map imbalanced dataset to the clusters
df_imbal["cluster"] = imbal_clusters

print("Real-World Cluster Distribution (Should be skewed):")
print(pd.Series(imbal_clusters).value_counts())



# =========================================
# STEP 2 - EXTRA PLOTS/ PRINT STATEMENTS
# =========================================


# PRINT LABELS IN EACH CLUSTER

# Is exactly the same code as seeing step 1 label breakdown per cluster
print("\n--- Phase 2: Cluster Interpretations (Real-World Data) ---")

unique_imbal_clusters = sorted(df_imbal['cluster'].unique())

for cid in unique_imbal_clusters:
    cluster_data = df_imbal[df_imbal['cluster'] == cid]
    composition = cluster_data['category'].value_counts()

    avg_bytes = cluster_data['bytes'].mean()
    avg_pkts = cluster_data['pkts'].mean()

    label_name = "NOISE" if cid == -1 else f"Cluster {cid}"
    
    print(f"\n[{label_name}] Total Points: {len(cluster_data)}")
    print(f"  -> Composition: {composition.to_dict()}")
    print(f"  -> Avg Profile: {avg_pkts:.1f} pkts, {avg_bytes:.1f} bytes")



# DIAGNOSTIC: STEP 2 CLUSTER MAP (K-MEANS)

print("\nGenerating 2D Cluster Space Plot...")

# 1. Configuration
# We use a sample because plotting 1.6 million points is slow and messy
SAMPLE_SIZE = 100000

# Check which dataframe you have available. 
# Ideally use 'df_imbal' (Step 2 output) or 'stats' (Step 1 output).
if 'df_imbal' in locals():
    plot_data = df_imbal.sample(n=min(SAMPLE_SIZE, len(df_imbal)), random_state=42)
else:
    print("Warning: 'df_imbal' dataframe not found. Ensure Step 2 has run.")
    plot_data = None

# 2. Prepare Data for PCA
# We need strictly feature columns, dropping 'cluster', 'saddr', 'stime', etc.
X_plot = plot_data[FEATURES].values
y_plot = plot_data['cluster'].values

# reuse the scaler and PCA from before
X_plot_scaled = scaler.transform(X_plot)
X_pca = pca.transform(X_plot_scaled)

plt.figure(figsize=(14, 10))

# Create scatter plot with seaborn
# "palette='tab20'" creates distinct colors. 
# We filter out Noise (-1) usually, but let's keep it to see everything.
sns.scatterplot(
    x=X_pca[:, 0], 
    y=X_pca[:, 1], 
    hue=y_plot, 
    palette="tab20",  # High contrast palette
    s=20,             # Dot size
    alpha=0.6,        # Transparency
    legend="full"
)

# Highlight Cluster 17 (Exfiltration) specifically
c17_mask = (y_plot == 17)
plt.scatter(
    X_pca[c17_mask, 0], 
    X_pca[c17_mask, 1], 
    c='black', 
    marker='x', 
    s=100, 
    linewidth=2,
    label='TARGET: Exfiltration (17)'
)

plt.title(f"Cluster Separation Map (PCA Projection) - {len(np.unique(y_plot))} Clusters")
plt.xlabel("Principal Component 1 (Variance)")
plt.ylabel("Principal Component 2 (Variance)")

# Move legend outside because 28 items is tall
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)

plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("cluster_map_step2.png", dpi=300)
plt.show()



# ==========================================
# FORENSIC: WHERE DID THE REAL ATTACKS GO? (KNN Version)
# ==========================================

print("\nGenerating 'Captured vs. Escaped' Plot...")

# --- CONFIGURATION: UPDATE THIS ---
# 1. Column name for the attack type in your CSV
TARGET_COL = 'category'  # e.g., 'label', 'attack_cat', 'class'

# 2. Value for "Theft" in that column
THEFT_LABEL = 'Theft'   # e.g., 'Analysis', 'Backdoor', or 1
# ----------------------------------

# 1. FIND THE REAL THEFT PACKETS (Ground Truth)
if 'df_imbal' in locals() and TARGET_COL in df_imbal.columns:
    # Filter for the specific attack class
    if df_imbal[TARGET_COL].dtype == 'object':
        real_theft_mask = df_imbal[TARGET_COL] == THEFT_LABEL
    else:
        real_theft_mask = df_imbal[TARGET_COL] == 1 
        
    # Get the features and the Assigned Cluster for these specific packets
    X_real_theft = df_imbal.loc[real_theft_mask, FEATURES]
    assigned_clusters = df_imbal.loc[real_theft_mask, 'cluster'] # The labels from Step 2
    
    print(f"Found {len(X_real_theft)} Real Theft Packets in original data.")
else:
    raise ValueError(f"Column '{TARGET_COL}' not found in df_imbal.")

# 2. SPLIT INTO "CAPTURED" (Cluster 24) vs "ESCAPED" (Others)
detected_mask = (assigned_clusters == 17)
missed_mask = ~detected_mask

# 3. PREPARE PLOT DATA
# We need PCA coordinates for the map
# Use pandas to wrap features to avoid scaler warnings
X_real_theft_scaled = scaler.transform(X_real_theft)
X_real_theft_pca = pca.transform(X_real_theft_scaled)

X_detected_pca = X_real_theft_pca[detected_mask]
X_missed_pca = X_real_theft_pca[missed_mask]
missed_labels = assigned_clusters[missed_mask] 

# 4. APPLY JITTER (Essential for visibility)
jitter_strength = 0.5 

# Jitter for captured
if len(X_detected_pca) > 0:
    j_det_x = np.random.uniform(-1, 1, size=len(X_detected_pca)) * jitter_strength
    j_det_y = np.random.uniform(-1, 1, size=len(X_detected_pca)) * jitter_strength
else:
    j_det_x, j_det_y = [], []

# Jitter for missed
if len(X_missed_pca) > 0:
    j_miss_x = np.random.uniform(-1, 1, size=len(X_missed_pca)) * jitter_strength
    j_miss_y = np.random.uniform(-1, 1, size=len(X_missed_pca)) * jitter_strength
else:
    j_miss_x, j_miss_y = [], []

# 5. THE PLOT
plt.figure(figsize=(12, 10))

# A. Plot CAPTURED (Red Xs)
if len(X_detected_pca) > 0:
    plt.scatter(
        X_detected_pca[:, 0] + j_det_x, 
        X_detected_pca[:, 1] + j_det_y, 
        c='red', 
        marker='x', 
        s=100, 
        linewidth=2,
        label=f'Captured by Cluster 17 ({len(X_detected_pca)} pkts)'
    )

# B. Plot MISSED (Colored Circles)
if len(X_missed_pca) > 0:
    plt.scatter(
        X_missed_pca[:, 0] + j_miss_x, 
        X_missed_pca[:, 1] + j_miss_y, 
        c=missed_labels, 
        cmap='tab20', 
        marker='o', 
        s=80, 
        edgecolors='black',
        alpha=0.8,
        label=f'Missed / Misclassified ({len(X_missed_pca)} pkts)'
    )

plt.title("Forensic Analysis: Fate of the Real Theft Packets (Step 2)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(loc='upper right')
plt.grid(True, alpha=0.3)
plt.savefig("captured_vs_escaped_knn.png", dpi=300)
plt.show()

# 6. FORENSIC REPORT
print("\n--- ATTACK DETECTION REPORT ---")
print(f"Total Real Attacks Traced: {len(X_real_theft)}")
print(f"Correctly Identified (Cluster 17): {len(X_detected_pca)}")
print(f"Missed (False Negatives): {len(X_missed_pca)}")
if len(X_missed_pca) > 0:
    print("Where the missed attacks went (Wrong Cluster IDs):")
    print(missed_labels.value_counts().head(5))






# ==========================================
# DIAGNOSTIC: BURST LENGTH (TRUE THEFT VS FALSE ALARM)
# ==========================================

print("\nAnalyzing Burst Composition in Cluster 17...")

# --- CONFIGURATION ---
TARGET_CLUSTER = 17      # The cluster ID you are analyzing
# ---------------------

# 1. SETUP MASKS
# Mask for "The Model thinks this is Theft" (Cluster 24)
is_cluster_target = (imbal_clusters == TARGET_CLUSTER)

# Mask for "This is ACTUALLY Theft" (Ground Truth)
# (Ensure df_imbal is available from Step 2)
if df_imbal[TARGET_COL].dtype == 'object':
    is_real_theft = (df_imbal[TARGET_COL] == THEFT_LABEL)
else:
    is_real_theft = (df_imbal[TARGET_COL] == 1)

# 2. IDENTIFY BURSTS (Contiguous runs of Cluster 24)
# We give every distinct 'run' of packets a unique ID
cluster_series = pd.Series(is_cluster_target)
state_changes = cluster_series.ne(cluster_series.shift())
run_ids = state_changes.cumsum()

# 3. ANALYZE EACH BURST
# We create a temporary DataFrame to group by these Run IDs
analysis_df = pd.DataFrame({
    'run_id': run_ids,
    'in_cluster': is_cluster_target,
    'is_theft': is_real_theft.values
})

# Filter to keep only the runs that are actually inside Cluster 24
target_runs = analysis_df[analysis_df['in_cluster'] == True]

# Group by Run ID to get stats for each burst
burst_stats = target_runs.groupby('run_id').agg(
    burst_length=('in_cluster', 'count'),      # How long is the burst?
    real_theft_count=('is_theft', 'sum')       # How many REAL theft packets are in it?
)

# 4. SPLIT INTO "TRUE ATTACKS" AND "FALSE ALARMS"
# True Attack Burst: Contains at least one real theft packet
true_attack_bursts = burst_stats[burst_stats['real_theft_count'] > 0]['burst_length']

# False Alarm Burst: Contains ZERO real theft packets (Pure Noise)
false_alarm_bursts = burst_stats[burst_stats['real_theft_count'] == 0]['burst_length']

print(f"Found {len(true_attack_bursts)} Valid Attack Bursts")
print(f"Found {len(false_alarm_bursts)} False Alarm Bursts")

# 5. PLOT OVERLAPPING HISTOGRAMS
plt.figure(figsize=(12, 7))

# Plot False Alarms (Noise) usually short, in Blue/Grey
sns.histplot(
    false_alarm_bursts, 
    color='grey', 
    label=f'False Alarms (Noise) - Mean: {false_alarm_bursts.mean():.1f}', 
    kde=False, 
    stat="density", # Normalize so we can compare shapes even if counts differ
    alpha=0.4,
    binwidth=2
)

# Plot True Attacks (Theft) in Red
sns.histplot(
    true_attack_bursts, 
    color='red', 
    label=f'True Theft Flows - Mean: {true_attack_bursts.mean():.1f}', 
    kde=True, 
    stat="density",
    alpha=0.5,
    binwidth=2
)

plt.axvline(x=20, color='black', linestyle='--', linewidth=2, label='Selected Length (20)')

plt.title(f"Burst Length Analysis: True Attacks vs. False Alarms (Cluster {TARGET_CLUSTER})")
plt.xlabel("Consecutive Packets (Burst Length)")
plt.ylabel("Density (Normalized Frequency)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("burst_length_comparison.png", dpi=300)
plt.show()

# 6. FORENSIC SUMMARY
print("\n--- FORENSIC INSIGHT ---")
print(f"True Attack Mean Length: {true_attack_bursts.mean():.2f}")
print(f"False Alarm Mean Length: {false_alarm_bursts.mean():.2f}")

if false_alarm_bursts.mean() < true_attack_bursts.mean():
    print("INSIGHT: False positives are significantly shorter than real attacks.")
    print("Recommendation: You can filter out noise by ignoring bursts < 5 packets.")



# ==========================================
# DIAGNOSTIC: INTERNAL CLUSTER ANATOMY (PCA)
# ==========================================
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

print("Generating Internal Cluster Anatomy Plot...")

# --- CONFIGURATION ---
TARGET_CLUSTER = 17        # <--- CONFIRM this is the cluster ID you want to inspect
LABEL_COL = 'category'   # The column with "Theft", "Normal", "DoS", etc.
THEFT_LABEL = 'Theft'      # The specific string/value for Theft in your dataset
# ---------------------

# 1. PREPARE THE DATA SUBSET
# We only want the indices belonging to the Target Cluster
cluster_mask = (imbal_clusters == TARGET_CLUSTER)
X_subset = X_imbal_scaled[cluster_mask]
y_subset_labels = df_imbal.loc[cluster_mask, LABEL_COL].values

print(f"Analyzing Cluster {TARGET_CLUSTER} containing {len(X_subset)} packets.")

# 2. RUN LOCAL PCA
# We re-run PCA *only* on this cluster. 
# Why? Global PCA focuses on separating Cluster 20 from Cluster 5.
# Local PCA focuses on the subtle differences INSIDE Cluster 20.
pca = PCA(n_components=2)
X_pca_local = pca.fit_transform(X_subset)

# 3. CREATE PLOTTING DATAFRAME
# We simplify the labels to just "Theft" vs "Other" for clarity
# (You can comment this out if you want to see exactly what the "Other" is)
simplified_labels = np.where(y_subset_labels == THEFT_LABEL, 'Target (Theft)', 'Noise (Other)')

plot_df = pd.DataFrame({
    'PC1': X_pca_local[:, 0],
    'PC2': X_pca_local[:, 1],
    'Label': simplified_labels,
    'True_Category': y_subset_labels # Keep original just in case
})

# 4. PLOT
plt.figure(figsize=(10, 8))
sns.scatterplot(
    data=plot_df, 
    x='PC1', 
    y='PC2', 
    hue='Label', 
    style='Label', # Different shapes for clarity
    palette={'Target (Theft)': 'red', 'Noise (Other)': 'grey'},
    alpha=0.6,
    s=60 # Dot size
)

plt.title(f"Internal Anatomy of Cluster {TARGET_CLUSTER}\n(Local PCA Projection)", fontsize=14)
plt.xlabel(f"Local PC1 ({pca.explained_variance_ratio_[0]:.1%} variance)")
plt.ylabel(f"Local PC2 ({pca.explained_variance_ratio_[1]:.1%} variance)")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(f"cluster_{TARGET_CLUSTER}_anatomy.png")
plt.show()



# ================================
# STEP 2.5 - TRAINING THE HMM
# ================================

# Optionally run step 2.5 + 3
if RECREATE_SEQUENCES:
    # Extract Sequences (acts as a tokeniser basically for my HMM)
    # We know the attack is continuous, so we slice rigidly
    training_sequences = []

    # Sort by time to preserve flow order
    # groupby("saddr"): This isolates each unique Source IP. You are telling the code: 
    # "Ignore everyone else. Let's look at exactly what Bot A did, from start to finish."
    # sort_values("stime"): This is crucial. It puts the packets in chronological order. Without this, 
    # you might learn that an Attack happens before a Scan, which destroys the cause-and-effect relationship (causality).


    # Instead of training on the imbalanced, meaning they'll be wrong transition probabilites, why don't I just use the imbalanced
    # as a way of showing information about things and a method that would lead to issues
    # then what I actually want is to 'cheat' and use the real labels as well as the clusters in some way to make
    # the transition table genuinely accurate, then there is a point of temperature scaling. Plus I can then
    # accurately use these new 'types' - meaning a combination of labels and cluster mappings (again to work out)
    # to recreate packet features and they won't then be rubbish like they would with contaminated clusters.
    for src, group in df_imbal.sort_values("stime").groupby("saddr"):
        seq = group["cluster"].values
        
        # Skip short sessions
        if len(seq) < SEQ_LENGTH:
            continue
        
        # Slice windows
        num_windows = (len(seq) - SEQ_LENGTH) // STRIDE + 1
        for i in range(num_windows):
            start = i * STRIDE
            end = start + SEQ_LENGTH
            training_sequences.append(seq[start:end])

    print(f"Extracted {len(training_sequences)} sequences for HMM training.")

    # Filter sequences to ensure they only contain known clusters
    # (Rare edge case where KNN predicts something wild, usually safe to skip)
    valid_seqs = []
    for s in training_sequences:
        valid_seqs.append(le.transform(s))

    X_hmm = np.concatenate(valid_seqs).reshape(-1, 1)
    lengths = [len(s) for s in valid_seqs]

    # Train HMM
    hmm = CategoricalHMM(n_components=len(le.classes_), n_iter=200, random_state=42, verbose=True, tol=1) #change tol back down, just want it to be quick for now
    hmm.fit(X_hmm, lengths)

    print("HMM Model Trained on Imbalanced Grammar.")



    # ==========================================
    # PHASE 3: SYNTHESIS (The Zero-Day)
    # ==========================================

    print("\n--- PHASE 3: Zero-Day Synthesis (Temperature Scaling) ---")

    def apply_temperature(trans_mat, T=1.0):
        # Log-domain scaling logic
        if T == 1.0: return trans_mat
        
        # Raise to power (1/T)
        # 0.0 probabilities stay 0.0 (Constraints preserved)
        scaled = np.power(trans_mat, 1.0 / T)
        
        # Re-normalize rows
        row_sums = scaled.sum(axis=1, keepdims=True)
        # Avoid division by zero
        row_sums[row_sums == 0] = 1.0
        
        return scaled / row_sums

    # 1. Generate Matrices
    matrix_original = hmm.transmat_
    matrix_novel = apply_temperature(matrix_original, T=TEMPERATURE)

    # 2. Visualize Comparison
    plt.figure(figsize=(14, 6))

    labels = [f"C{c}\n({cluster_to_mitre.get(c, 'Unk')})" for c in le.classes_]

    plt.subplot(1, 2, 1)
    sns.heatmap(matrix_original, annot=True, fmt=".2f", cmap="Blues", 
                xticklabels=labels, yticklabels=labels)
    plt.title("Original Grammar (Rigid/Imbalanced)")

    plt.subplot(1, 2, 2)
    sns.heatmap(matrix_novel, annot=True, fmt=".2f", cmap="Reds", 
                xticklabels=labels, yticklabels=labels)
    plt.title(f"Synthesized Grammar (T={TEMPERATURE})")

    plt.tight_layout()
    plt.show()

    # 3. Generate Novel Sequences
    def generate_sequences(trans_mat, start_probs, n_seqs, length):
        n_states = trans_mat.shape[0]
        generated = []
        
        for _ in range(n_seqs):
            # Start state
            curr = np.random.choice(n_states, p=start_probs)
            seq = [curr]
            
            # Walk
            for _ in range(length - 1):
                probs = trans_mat[curr]
                # Normalize for safety
                probs /= probs.sum()
                
                next_state = np.random.choice(n_states, p=probs)
                seq.append(next_state)
                curr = next_state
                
            generated.append(seq)
        return np.array(generated)

    novel_seqs_indices = generate_sequences(matrix_novel, hmm.startprob_, 10000, SEQ_LENGTH)

    # 4. Decode and Print Sample
    # Inverse transform: 0..N -> Cluster IDs (-1, 0, 1..)
    sample_idx = novel_seqs_indices[0]
    sample_clusters = le.inverse_transform(sample_idx)
    sample_labels = [cluster_to_mitre.get(c, "Unknown") for c in sample_clusters]

    print(f"\nGenerated {len(novel_seqs_indices)} novel sequences.")
    print("Sample Zero-Day Attack Graph:")
    print(" -> ".join(sample_labels[:6]) + "...")

    # 5. Save for Step 4 (CVAE)
    # We save the INDICES (0..N) because the CVAE embedding layer needs 0-indexed integers
    np.save(OUTPUT_SEQ_FILE, novel_seqs_indices)
    print(f"Saved sequences to {OUTPUT_SEQ_FILE}")

else:
    print("Sequences already generated, skipping step")












# ==========================================
# STEP 4 - CVAE
# ==========================================

import torch

# Define the device (uses GPU if available, else CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

BATCH_SIZE = 128
LATENT_DIM = 16      # Dimension of random noise (z)
EPOCHS = 50          # Training duration
LR = 1e-3            # Learning Rate
SEQ_LENGTH = 20      # (Kept for HMM compatibility, unused by CVAE)


# ==========================================
# 1. DATA PREPARATION (Corrected for Zero-Day Generation)
# ==========================================
print("Preparing CVAE Training Data (Packet-Level)...")

# --- CRITICAL CHANGE 1: Use Pure Data, not Polluted Data ---
# We use X_bal because Cluster 20 is 100% pure Exfiltration here.
# (df_imbal has 29,000 DoS packets wrongly labeled as Cluster 20)
X_source = X_bal.copy()
y_source = bal_clusters.copy()

# --- CRITICAL CHANGE 2: Oversample the Target (Focus) ---
# The model will ignore Cluster 20 if it only sees 14 samples.
# We multiply it so the model takes it seriously.
TARGET_CLUSTER = 17
OVERSAMPLE_FACTOR = 500  # Turn 14 packets into ~7,000

# Find the target rows
target_indices = np.where(y_source == TARGET_CLUSTER)[0]
target_data_original = X_source.iloc[target_indices].values
target_labels_original = y_source[target_indices]

# Instead of exact copies, we create noisy versions
augmented_features = [X_source.values] # Start with original background data
augmented_labels = [y_source]

OVERSAMPLE_FACTOR = 50
noise_level = 0.1 # Add 10% variance to the standard deviation

print(f"Augmenting {len(target_indices)} samples x {OVERSAMPLE_FACTOR} with noise...")

for _ in range(OVERSAMPLE_FACTOR):
    # 1. Create a copy
    noisy_batch = target_data_original.copy()
    
    # 2. Add Gaussian Noise (Jitter)
    # We use the global scaler's scale_ to ensure noise is proportional to each feature
    jitter = np.random.normal(0, noise_level, noisy_batch.shape) 
    
    # 3. Add noise (but keep integers like 'pkts' somewhat sensible later)
    noisy_batch = noisy_batch + jitter
    
    augmented_features.append(noisy_batch)
    augmented_labels.append(target_labels_original)

# Combine
X_cvae = np.vstack(augmented_features).astype(np.float32)
y_cvae = np.concatenate(augmented_labels).astype(np.int64)

# Encode Labels
le_cvae = LabelEncoder()
y_cvae_enc = le_cvae.fit_transform(y_cvae)
num_classes = len(le_cvae.classes_)

# Scale (If X_bal was raw. If X_bal was already scaled, skip this!)
# Assuming X_bal is raw features based on your earlier scripts:
X_cvae_scaled = scaler.transform(X_cvae)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_cvae_scaled, y_cvae_enc, test_size=0.2, random_state=42, stratify=y_cvae_enc
)

train_ds = TensorDataset(torch.tensor(X_train), torch.tensor(y_train))
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)

print(f"Final Training Data Shape: {X_train.shape}")

# ==========================================
# 2. CVAE MODEL DEFINITION (Packet-Level)
# ==========================================
class PacketCVAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, num_classes):
        super(PacketCVAE, self).__init__()
        self.input_dim = input_dim
        
        # Embed Class ID -> Vector of size 5
        self.embed = nn.Embedding(num_classes, 5)
        
        # --- ENCODER ---
        # Input = Features + Class_Embedding (5)
        self.enc_input_size = input_dim + 5
        self.enc1 = nn.Linear(self.enc_input_size, hidden_dim)
        self.enc2 = nn.Linear(hidden_dim, hidden_dim // 2)
        
        self.fc_mu = nn.Linear(hidden_dim // 2, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim // 2, latent_dim)
        
        # --- DECODER ---
        # Input = Latent(z) + Class_Embedding (5)
        self.dec_input_size = latent_dim + 5
        self.dec1 = nn.Linear(self.dec_input_size, hidden_dim // 2)
        self.dec2 = nn.Linear(hidden_dim // 2, hidden_dim)
        self.dec_out = nn.Linear(hidden_dim, input_dim)  # Output is just features
        
    def encode(self, x, c):
        # x is (Batch, Features)
        # c is (Batch) -> embed -> (Batch, 5)
        c_emb = self.embed(c)
        in_vec = torch.cat([x, c_emb], dim=1)
        
        h = F.relu(self.enc1(in_vec))
        h = F.relu(self.enc2(h))
        return self.fc_mu(h), self.fc_logvar(h)
    
    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std
    
    def decode(self, z, c):
        c_emb = self.embed(c)
        in_vec = torch.cat([z, c_emb], dim=1)
        
        h = F.relu(self.dec1(in_vec))
        h = F.relu(self.dec2(h))
        return self.dec_out(h) # Returns (Batch, Features)
        
    def forward(self, x, c):
        mu, logvar = self.encode(x, c)
        z = self.reparameterize(mu, logvar)
        recon_x = self.decode(z, c)
        return recon_x, mu, logvar

# Instantiate the simpler model
# Note: We removed 'seq_len' from the arguments
model = PacketCVAE(
    input_dim=X_train.shape[1], # Should be 14 features
    hidden_dim=128,
    latent_dim=LATENT_DIM,
    num_classes=len(le.classes_)
).to(device)

optimizer = optim.Adam(model.parameters(), lr=LR)

def loss_fn(recon_x, x, mu, logvar):
    MSE = F.mse_loss(recon_x, x, reduction='sum')
    KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return MSE + KLD

# ==========================================
# 3. TRAINING LOOP
# ==========================================
print("Starting Training...")
model.train()

for epoch in range(EPOCHS):
    total_loss = 0
    for bx, bc in train_loader:
        bx, bc = bx.to(device), bc.to(device)
        
        optimizer.zero_grad()
        recon, mu, logvar = model(bx, bc)
        loss = loss_fn(recon, bx, mu, logvar)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        
    if (epoch+1) % 5 == 0:
        avg = total_loss / len(train_loader.dataset)
        print(f"Epoch {epoch+1}/{EPOCHS}: Loss {avg:.2f}")

print("CVAE Trained.")


# ==========================================
# STEP 5: SYNTHESIS, CLEANING & VISUALIZATION
# ==========================================

print("\n--- PHASE 5: Generating & Cleaning Zero-Day Attack Traffic ---")

# ==========================================
# FIX: RE-INITIALIZE LABEL ENCODER
# ==========================================
from sklearn.preprocessing import LabelEncoder

# We need to make sure the encoder knows every possible cluster ID 
# that the model was trained on. We use the balanced dataset for this source of truth.
print("Re-fitting Label Encoder to ensure matching IDs...")
le_cvae = LabelEncoder()
le_cvae.fit(bal_clusters)  # Fits on the original Cluster IDs (-1, 0, 1... 28)

# Double check that Cluster 20 is in there
if TARGET_CLUSTER not in le_cvae.classes_:
    print(f"CRITICAL WARNING: Target Cluster {TARGET_CLUSTER} not found in encoder!")
    # Force add it if missing (hack fix)
    le_cvae.classes_ = np.append(le_cvae.classes_, TARGET_CLUSTER)
    le_cvae.classes_.sort()

# 1. Load the Attack Scripts (Sequences from HMM)
novel_seqs = np.load(OUTPUT_SEQ_FILE)
target_seqs = []

for seq in novel_seqs:
    if TARGET_CLUSTER in seq:
        target_seqs.append(seq)

if len(target_seqs) == 0:
    print("WARNING: No Exfiltration sequences found! Using top 100 sequences.")
    target_seqs = novel_seqs[:100]

# Flatten for CVAE
flat_labels = np.concatenate(target_seqs)
n_packets = len(flat_labels)

# 2. Generate Raw Features (The "Actor")
label_tensor = torch.tensor(le_cvae.transform(flat_labels)).long().to(device)
z_noise = torch.randn(n_packets, LATENT_DIM).to(device)

model.eval()
with torch.no_grad():
    generated_features_scaled = model.decode(z_noise, label_tensor)

generated_features = scaler.inverse_transform(generated_features_scaled.cpu().numpy())

# 3. Create DataFrame
df_zero_day = pd.DataFrame(generated_features, columns=FEATURES)
df_zero_day['cluster'] = flat_labels
df_zero_day['type'] = 'Zero-Day'

# ==========================================
# PHYSICS VALIDATION (The "Sanity Check")
# ==========================================
print("Applying Physics Post-Processing...")

# Rule A: Integers Only for Counters
df_zero_day["pkts"] = df_zero_day["pkts"].round().astype(int).clip(lower=1)
df_zero_day["spkts"] = df_zero_day["spkts"].round().astype(int).clip(lower=0)
df_zero_day["dpkts"] = df_zero_day["dpkts"].round().astype(int).clip(lower=0)

# Rule B: Time cannot be negative
df_zero_day["dur"] = df_zero_day["dur"].clip(lower=0.0)

# Rule C: Bytes must be physically possible
# Min packet size ~42 bytes (Headers). Total bytes >= pkts * 42
min_bytes = df_zero_day["pkts"] * 42
df_zero_day["bytes"] = df_zero_day["bytes"].round().astype(int)
df_zero_day["bytes"] = np.maximum(df_zero_day["bytes"], min_bytes)

# Rule D: Recalculate Rates (Consistency Check)
# AI predicts Rate, Duration, and Packets independently. They might not match.
# We trust Pkts & Dur, and overwrite Rate to be mathematically perfect.
# Rate = Pkts / Dur
df_zero_day["rate"] = np.where(df_zero_day["dur"] > 1e-6, 
                               df_zero_day["pkts"] / df_zero_day["dur"], 
                               0)

# Rule E: Recalculate Mean
df_zero_day["mean"] = df_zero_day["bytes"] / df_zero_day["pkts"]

# Save Cleaned Data
OUTPUT_CSV = "Zero_Day_Attack_Cleaned.csv"
df_zero_day.to_csv(OUTPUT_CSV, index=False)
print(f"Generated {len(df_zero_day)} valid packets. Saved to {OUTPUT_CSV}")



# ==========================================
# DIAGNOSTIC PLOT (No Filtering)
# ==========================================
print("\n--- DIAGNOSTIC: Range Check ---")

# 1. Get Data
real_c20 = X_bal[bal_clusters == TARGET_CLUSTER]
real_c20_scaled = scaler.transform(real_c20)
real_pca = pca.transform(real_c20_scaled)

syn_c20 = df_zero_day[df_zero_day['cluster'] == TARGET_CLUSTER][FEATURES]
syn_c20_scaled = scaler.transform(syn_c20)
syn_pca = pca.transform(syn_c20_scaled)

# 2. Print Coordinates (The most important part)
print(f"Real Data X Range: {real_pca[:,0].min():.2f} to {real_pca[:,0].max():.2f}")
print(f"Real Data Y Range: {real_pca[:,1].min():.2f} to {real_pca[:,1].max():.2f}")
print("-" * 30)
print(f"Syn Data X Range:  {syn_pca[:,0].min():.2f} to {syn_pca[:,0].max():.2f}")
print(f"Syn Data Y Range:  {syn_pca[:,1].min():.2f} to {syn_pca[:,1].max():.2f}")

# 3. Plot EVERYTHING (Let Matplotlib decide the zoom)
plt.figure(figsize=(10, 7))
plt.scatter(syn_pca[:, 0], syn_pca[:, 1], c='red', marker='x', alpha=0.5, label='Synthetic')
plt.scatter(real_pca[:, 0], real_pca[:, 1], c='blue', s=100, edgecolors='black', label='Real')
plt.title("Diagnostic Plot: Where is the Synthetic Data?")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()



# ==========================================
# VISUALIZATION (With Outlier Removal)
# ==========================================
print("\nGenerating Dissertation Plot: 'The Sniper Scope'...")

# 1. Get Real Data (The Anchor)
real_c20 = X_bal[bal_clusters == TARGET_CLUSTER]
real_c20_scaled = scaler.transform(real_c20)
real_pca = pca.transform(real_c20_scaled)

# 2. Get Synthetic Data
syn_c20 = df_zero_day[df_zero_day['cluster'] == TARGET_CLUSTER][FEATURES]
syn_c20_scaled = scaler.transform(syn_c20)
syn_pca = pca.transform(syn_c20_scaled)

# --- FIX START: REMOVE OUTLIERS ---
# We calculate the bounds of the REAL data
x_min, x_max = real_pca[:, 0].min(), real_pca[:, 0].max()
y_min, y_max = real_pca[:, 1].min(), real_pca[:, 1].max()

# Define a "Safe Zone" (e.g., add margin of 10 units around real data)
margin = 5.0 
mask_x = (syn_pca[:, 0] >= x_min - margin) & (syn_pca[:, 0] <= x_max + margin)
mask_y = (syn_pca[:, 1] >= y_min - margin) & (syn_pca[:, 1] <= y_max + margin)
clean_mask = mask_x & mask_y

# Apply filter
syn_pca_clean = syn_pca[clean_mask]
print(f"Plotting {len(syn_pca_clean)} points (Filtered {len(syn_pca) - len(syn_pca_clean)} outliers)")
# --- FIX END ---

# 3. Plot
plt.figure(figsize=(10, 7))

# Plot Filtered Synthetic
plt.scatter(syn_pca_clean[:, 0], syn_pca_clean[:, 1], 
            c='red', marker='x', alpha=0.3, label='Synthetic Zero-Day (Variations)')

# Plot Real
plt.scatter(real_pca[:, 0], real_pca[:, 1], 
            c='blue', s=100, edgecolors='black', label='Real Exfiltration (Seed)')

plt.title(f"Visual Proof of Zero-Day Generation (Cluster {TARGET_CLUSTER})")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("zero_day_pca_zoomed.png", dpi=300)
plt.show()














# ==========================================
# CONFIGURATION
# ==========================================
REAL_DATA_FILE = "UNSW_2018_IoT_Botnet_Full5pc_4.csv"
SYNTHETIC_DATA_FILE = "Zero_Day_Attack_Cleaned.csv"

FEATURES = [
    "dur", "pkts", "spkts", "dpkts", 
    "bytes", "sbytes", "dbytes",
    "rate", "srate", "drate", 
    "mean", "stddev", "min", "max"
]

print("--- STEP 5: Visual Validation (Fixed) ---")

# 1. LOAD DATA
print("Loading Real Data...")
df_real = pd.read_csv(REAL_DATA_FILE, nrows=50000) 
if 'attack_cat' in df_real.columns:
    df_real.rename(columns={'attack_cat': 'category'}, inplace=True)

# Sample random points
df_real = df_real[FEATURES].replace([np.inf, -np.inf], np.nan).dropna().sample(n=3000, random_state=42)
df_real["Label"] = "Real"

print("Loading Synthetic Data...")
df_synth = pd.read_csv(SYNTHETIC_DATA_FILE)
df_synth = df_synth[FEATURES]
df_synth["Label"] = "Synthetic"

print(f"Comparison: {len(df_real)} Real vs {len(df_synth)} Synthetic samples.")

# 2. PCA PROJECTION
combined_data = pd.concat([df_real[FEATURES], df_synth[FEATURES]])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(combined_data)

pca = PCA(n_components=2)
pca_result = pca.fit_transform(scaled_data)

# Split back
real_pca = pca_result[:len(df_real)]
synth_pca = pca_result[len(df_real):]

# 3. PLOT: Side-by-Side and Overlay
plt.figure(figsize=(18, 6))

# Subplot 1: Real Only
plt.subplot(1, 3, 1)
plt.scatter(real_pca[:, 0], real_pca[:, 1], c='blue', alpha=0.2, s=10, label='Real')
plt.title("Real Traffic Only")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend()
plt.grid(True, alpha=0.3)

# Subplot 2: Synthetic Only
plt.subplot(1, 3, 2)
plt.scatter(synth_pca[:, 0], synth_pca[:, 1], c='red', alpha=0.2, s=10, marker='x', label='Synthetic')
plt.title("Synthetic Zero-Day Only")
plt.xlabel("PC1")
plt.yticks([]) # Hide Y axis for cleaner look
plt.legend()
plt.grid(True, alpha=0.3)

# Subplot 3: The Overlay (With Fixed Alpha)
plt.subplot(1, 3, 3)
# Plot Synthetic FIRST (Bottom layer)
plt.scatter(synth_pca[:, 0], synth_pca[:, 1], c='red', alpha=0.15, s=20, marker='x', label='Synthetic')
# Plot Real SECOND (Top layer) - so Blue shows up on top of Red
plt.scatter(real_pca[:, 0], real_pca[:, 1], c='blue', alpha=0.15, s=10, label='Real')

plt.title("Overlay (Real on Top)")
plt.xlabel("PC1")
plt.yticks([])
plt.legend()
plt.grid(True, alpha=0.3)

# Optional: Zoom in if outliers are squashing the plot
# Uncomment these lines if the main blob is still too small
# plt.xlim(-5, 10)
# plt.ylim(-5, 10)

plt.tight_layout()
plt.savefig("plot_pca_better.png")
plt.show()

# 4. Feature Check (Histograms)
# ... (Inside Step 5) ...

print("Generating Feature Histograms...")
key_features = ["dur", "bytes", "pkts", "rate"]

plt.figure(figsize=(15, 10))
for i, feature in enumerate(key_features):
    plt.subplot(2, 2, i+1)
    
    # 1. Get Data
    real_vals = df_real[feature].copy()
    synth_vals = df_synth[feature].copy()
    
    # 2. Add "Jitter" to fix 0-variance crash
    # We add random noise approx 0.000001 to spread the zeros out slightly
    real_vals += np.random.normal(0, 1e-6, len(real_vals))
    synth_vals += np.random.normal(0, 1e-6, len(synth_vals))
    
    # 3. Safe Log Scale (Clip negative jitter)
    real_vals = np.maximum(real_vals, 1e-6)
    synth_vals = np.maximum(synth_vals, 1e-6)
    
    # 4. Plot
    sns.kdeplot(real_vals, fill=True, color="blue", label="Real", alpha=0.3, log_scale=True, warn_singular=False)
    sns.kdeplot(synth_vals, fill=True, color="red", label="Synthetic", alpha=0.3, log_scale=True, warn_singular=False)
    
    plt.title(f"Distribution of '{feature}' (Log Scale)")
    plt.legend()

plt.tight_layout()
plt.savefig("plot_feature_distributions_robust.png")
plt.show()



# Config
REAL_FILE = "UNSW_2018_IoT_Botnet_Full5pc_4.csv"
SYNTH_FILE = "synthetic_traffic_cleaned.csv"
FEATURES = ["dur", "pkts", "bytes", "rate"] # Key metrics

print("--- STEP 6: Numerical Evaluation ---")

# 1. Load Data
df_real = pd.read_csv(REAL_FILE, nrows=50000)
if 'attack_cat' in df_real.columns:
    df_real.rename(columns={'attack_cat': 'category'}, inplace=True)
df_real = df_real[FEATURES].dropna()

df_synth = pd.read_csv(SYNTH_FILE)
df_synth = df_synth[FEATURES].dropna()

# 2. Diversity Score (Variance)
# Higher variance = More diverse attack strategies
var_real = df_real.var().mean()
var_synth = df_synth.var().mean()

print(f"\n1. Diversity (Mean Variance):")
print(f"   Real Traffic:      {var_real:.2f}")
print(f"   Synthetic Zero-Day:{var_synth:.2f}")
print(f"   >> Improvement:    {((var_synth - var_real)/var_real)*100:.1f}%")

# 3. Novelty Score (Max Intensity)
# Did we find bigger attacks?
max_bytes_real = df_real["bytes"].max()
max_bytes_synth = df_synth["bytes"].max()

print(f"\n2. Intensity Ceiling (Max Bytes):")
print(f"   Real Traffic:      {max_bytes_real:,.0f}")
print(f"   Synthetic Zero-Day:{max_bytes_synth:,.0f}")

# 4. Coverage (Bounding Box)
# What % of Synthetic data falls OUTSIDE the Real min/max ranges?
# (This is the % of "Zero-Day" packets)
outliers = 0
for feat in FEATURES:
    min_val = df_real[feat].quantile(0.01)
    max_val = df_real[feat].quantile(0.99)
    
    # Count how many synthetic rows are outside this range
    mask = (df_synth[feat] < min_val) | (df_synth[feat] > max_val)
    outliers += mask.sum()

# Average outlier rate across features
novelty_score = (outliers / (len(df_synth) * len(FEATURES))) * 100

print(f"\n3. Zero-Day Score:")
print(f"   {novelty_score:.1f}% of generated traffic falls outside the 99% confidence interval of real traffic.")
print("   (This confirms the 'Red Tail' seen in your PCA plots)")







import pandas as pd
import numpy as np
import time
import os

# ==========================================
# CONFIGURATION
# ==========================================
SYNTHETIC_INPUT = "synthetic_traffic_cleaned.csv"
# CHANGED: Use the balanced file because it GUARANTEES we have Theft/Recon rows
REAL_SOURCE = "balanced_bot_iot.csv" 
OUTPUT_FILE = "synthetic_traffic_final_v2.csv"

GENERATED_FEATURES = [
    "dur", "pkts", "spkts", "dpkts", 
    "bytes", "sbytes", "dbytes",
    "rate", "srate", "drate", 
    "mean", "stddev", "min", "max"
]

HIGH_BYTE_THRESHOLD = 2000
HIGH_RATE_THRESHOLD = 100

print("--- STEP 7: Full Context Imputation (Fast) ---")

# 1. Load Data
print(f"Loading Templates from {REAL_SOURCE}...")
if not os.path.exists(REAL_SOURCE):
    print(f"Error: {REAL_SOURCE} missing. Did you run the 'Create Balanced' step?")
    exit()

df_real = pd.read_csv(REAL_SOURCE)

# Ensure column names are standardized
if 'attack_cat' in df_real.columns:
    df_real.rename(columns={'attack_cat': 'category'}, inplace=True)

print(f"Loading {SYNTHETIC_INPUT}...")
df_synth = pd.read_csv(SYNTHETIC_INPUT)

# 2. Create Template Libraries
print("Indexing Context Libraries...")

idx_ddos = df_real[df_real["category"] == "DDoS"].index.tolist()
idx_recon = df_real[df_real["category"] == "Reconnaissance"].index.tolist()
# Check for Theft (some versions of the dataset label it differently)
idx_theft = df_real[df_real["category"].str.contains("Theft|Exfiltration", case=False, na=False)].index.tolist()

# FAILSAFES
if len(idx_ddos) == 0: 
    # If DDoS is missing (unlikely), try 'DoS'
    idx_ddos = df_real[df_real["category"] == "DoS"].index.tolist()

if len(idx_recon) == 0:
    print("Warning: Recon templates missing. Fallback to DDoS.")
    idx_recon = idx_ddos
    
if len(idx_theft) == 0:
    print("Warning: Theft templates missing. Fallback to Recon.")
    idx_theft = idx_recon

print(f"  - DDoS Templates: {len(idx_ddos)}")
print(f"  - Theft Templates: {len(idx_theft)}")
print(f"  - Recon Templates: {len(idx_recon)}")

# 3. Smart Imputation
print("Synthesizing Final Dataset...")
final_rows = []

bot_ips = ["192.168.100.147", "192.168.100.148", "192.168.100.149", "192.168.100.150"]
victim_ip = "192.168.100.3"

num_rows = len(df_synth)
current_ids = np.arange(9000000, 9000000 + num_rows)
current_seqs = np.arange(100000, 100000 + num_rows)
timestamps = np.linspace(time.time(), time.time() + 600, num_rows)

for i, row in df_synth.iterrows():
    # A. Pick Template
    if row["bytes"] > HIGH_BYTE_THRESHOLD:
        chosen_idx = np.random.choice(idx_theft)
    elif row["rate"] > HIGH_RATE_THRESHOLD:
        chosen_idx = np.random.choice(idx_ddos)
    else:
        chosen_idx = np.random.choice(idx_recon)
    
    # Copy Costume (Real Context)
    template_row = df_real.loc[chosen_idx].to_dict()
    
    # B. Overwrite Body (Synthetic Features)
    for feat in GENERATED_FEATURES:
        template_row[feat] = row[feat]
        
    # C. Update Metadata
    template_row["pkSeqID"] = current_ids[i]
    template_row["seq"] = current_seqs[i]
    template_row["stime"] = timestamps[i]
    template_row["ltime"] = timestamps[i] + row["dur"]
    template_row["saddr"] = np.random.choice(bot_ips)
    template_row["daddr"] = victim_ip
    template_row["sport"] = np.random.randint(1024, 65535)
    template_row["dport"] = 80
    template_row["attack"] = 1
    
    final_rows.append(template_row)

# 4. Save
df_final = pd.DataFrame(final_rows)

# Align columns to match the Real file's structure
header_cols = df_real.columns.tolist()
df_final = df_final[header_cols]

# Validation
print("\n--- Validation Check ---")
col_check = "TnBPSrcIP" 
if col_check in df_final.columns:
    print(f"Sample {col_check} (Should be real numbers):")
    print(df_final[col_check].head(5).tolist())

df_final.to_csv(OUTPUT_FILE, index=False)
print(f"\nSaved final dataset to '{OUTPUT_FILE}'")